### ISSUE TITLE
Filter Format seems incorrect?

### ISSUE THREAD

**Issue by kelenakamura** [bejamas/gatsby-storyblok-image#13]
There seems to be issues with the filter format for generating a storyblok image path. There should be no colon between the filter name and the value.

https://github.com/bejamas/gatsby-storyblok-image/blob/master/src/utils/buildImageUrl.js#L19

filters:quality**:**(80) should be filters:quality(80)

https://www.storyblok.com/docs/image-service

**Comment by kelenakamura** [comment]
looks like there's already a pr with this update - https://github.com/bejamas/gatsby-storyblok-image/pull/12

**Comment by arkgor** [comment]
Fixed in #12
