### ISSUE TITLE
Add support for the new gatsby-plugin-image

### ISSUE THREAD

**Issue by Figumari** [bejamas/gatsby-storyblok-image#24]
Please add support for the new gatsby image plugin: https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-image#readme

**Comment by arkgor** [comment]
@Figumari the easiest solution would be to pass the image src directly to the gatsby-image-plugin (StaticImage) - have you tried it?

**Comment by rubeonline** [comment]
@arkgor I tried it and that does not work:
https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image#restrictions-on-using-staticimage

**Comment by arkgor** [comment]
@rubeonline one thing I noticed, storyblok return the image/asset url without http(s) (like: `//a.storyblok.com/...`) and in that format it didn't work for me, but after I put `https` it worked fine, can you check?

**Comment by fcisio** [comment]
> @arkgor I tried it and that does not work:

Yeah, only `Dynamic images` (so input from GarphQL) accept props from the parent.

But, but we're already using a lot of that between Gatsby & Storyblok. I think we could replicate what's done with [Dynamic images](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/#dynamic-images).

But at that point, this might be worth it to create a package `gatsby-storyblok-image-plugin`.

**Comment by saschaklatt** [comment]
Is there any update on this? `gatsby-image` is officially deprecated.

**Comment by fcisio** [comment]
@klattiation Not possible, It's a limitation from Storyblok.

But they should be working on an official "Storyblok Plugin for Gatsby Image Plugin".

It should be the [next thing in their roadmap](https://feedback.storyblok.com/b/feature-requests/create-official-storyblok-plugin-for-gatsby-image-plugin/)

**Comment by saschaklatt** [comment]
@fcisio alright thanks!

**Comment by lisilinhart** [comment]
We added some support for gatsby images in the `3.1.0` of gatsby source storyblok: https://github.com/storyblok/gatsby-source-storyblok

**Comment by fcisio** [comment]
Hey everyone, following with @lisilinhart update above, I think we'd be all set for an upgrade.

I was thinking we could scratch pretty much all the current code, and simply extend the native `gatsby-plugin-image` components.

Basically, we only need to use the CDN url when:
1.  inside the editor `if (location.search.includes('_storyblok'))`
2. no data is available from the GraphQL query, but there is a CDN url.

That way, no CDN url should make it to the prod, and we still have images that work inside the editor.

> We can also get additional values (width, height, ...) when fields are integrated via the V2 Editor. So we wouldn't need to get those props by dissecting the URL anymore.

---

I'll be drafting this on a project, then I can help with the implementation if needed 🎉

**Comment by nonjene** [comment]
I am making an update to support gatsby-plugin-image, with typing support 😀

**Comment by nonjene** [comment]
> I am making an update to support gatsby-plugin-image, with typing support 😀

https://github.com/nonjene/gatsby-plugin-storyblok-image I have rewritten it based on this plugin with typescript.
